import { Injectable } from '@nestjs/common'
import type {
  LlmProvider,
  LlmProviderRequest,
  LlmProviderResponse,
} from './llm.types.js'
import {
  createUsage,
  estimateMessageTokens,
  estimateTokens,
} from './llm.utils.js'

const mockJsonPrefix = 'MOCK_JSON:'

@Injectable()
export class MockLlmProvider implements LlmProvider {
  readonly providerId = 'mock' as const

  async completeJson(
    request: LlmProviderRequest,
  ): Promise<LlmProviderResponse> {
    const rawText = this.resolveMockJson(request)

    return {
      rawText,
      usage: createUsage(
        estimateMessageTokens(request.messages),
        estimateTokens(rawText),
      ),
      providerId: this.providerId,
      model: request.model,
    }
  }

  private resolveMockJson(request: LlmProviderRequest) {
    const explicitMock = [...request.messages]
      .reverse()
      .map((message) => message.content)
      .find((content) => content.includes(mockJsonPrefix))

    if (explicitMock) {
      return explicitMock.slice(
        explicitMock.indexOf(mockJsonPrefix) + mockJsonPrefix.length,
      )
    }

    if (request.taskName === 'triage/v1') {
      return JSON.stringify(this.createTriageResponse(request))
    }

    if (request.taskName.startsWith('agents/')) {
      return JSON.stringify(this.createAgentResponse(request))
    }

    return JSON.stringify({
      summary: `Mock response for ${request.taskName}`,
    })
  }

  private createTriageResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const text = [
      payload.idea?.rawIdea,
      payload.idea?.targetAudience,
      ...(payload.idea?.strategicGoals ?? []),
      ...(payload.idea?.technicalPreferences ?? []),
      ...(payload.idea?.constraints ?? []),
    ]
      .join(' ')
      .toLowerCase()
    const securitySensitive =
      payload.shieldMaxSeverity === 'high' ||
      /security|appsec|auth|payment|fintech|compliance|privacy/.test(text)
    const mobileDomain = /mobile|ios|android|react native/.test(text)
    const complexity = /enterprise|multi-tenant|temporal|orchestrator|scale/.test(
      text,
    )
      ? 'high'
      : text.length > 600
        ? 'medium'
        : 'low'
    const recommendedAgents = [
      'product_manager',
      'critic',
      'moderator',
      ...(securitySensitive ? ['security_expert'] : []),
      ...(complexity === 'high' ? ['software_architect'] : []),
      ...(/market|competitor|pricing|gtm|go-to-market/.test(text)
        ? ['market_researcher']
        : []),
      ...(mobileDomain ? ['mobile_ux_expert'] : []),
    ].slice(0, 7)

    return {
      domain: mobileDomain ? 'mobile' : securitySensitive ? 'security' : 'software',
      subdomain: securitySensitive ? 'Security-sensitive software' : 'SaaS planning',
      complexity,
      marketConfidence: /new market|unknown|validate|competitor/.test(text)
        ? 'low'
        : 'medium',
      securitySensitivity: securitySensitive ? 'high' : 'medium',
      recommendedRunMode: recommendedAgents.length > 4 ? 'deep' : 'standard',
      recommendedAgents,
      estimatedDurationSeconds: recommendedAgents.length > 4 ? 150 : 60,
      estimatedMaxCostUsd: recommendedAgents.length > 4 ? 1.25 : 0.5,
      reasoningSummary:
        'Mock provider response generated through the prompt-driven LLM gateway.',
    }
  }

  private createAgentResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const idea = payload.draftRun?.idea?.rawIdea ?? 'the submitted idea'
    const targetAudience =
      payload.draftRun?.idea?.targetAudience ?? 'early adopters'
    const role = request.taskName.split('/')[1] ?? 'agent'

    return {
      summary: `${this.formatRole(role)} reviewed "${idea}" for ${targetAudience}.`,
      strengths: [
        'The workflow is structured and non-chat by design.',
        'Human review reduces the risk of expensive incorrect execution.',
      ],
      weaknesses: [
        'The current response is generated by the local mock provider.',
        'Real model quality still needs validation with provider adapters.',
      ],
      risks: [
        'Artifact quality can look convincing before assumptions are validated.',
      ],
      recommendations: [
        'Keep schema validation mandatory for every agent response.',
        'Track prompt version and model metadata for each output.',
      ],
      roleSpecificInsights: {
        role,
        providerMode: 'mock',
      },
    }
  }

  private extractPayload(request: LlmProviderRequest) {
    const content = [...request.messages]
      .reverse()
      .map((message) => message.content)
      .find((message) => message.includes('INPUT_JSON:'))

    if (!content) {
      return {}
    }

    try {
      return JSON.parse(content.slice(content.indexOf('INPUT_JSON:') + 11)) as {
        idea?: {
          rawIdea?: string
          targetAudience?: string
          strategicGoals?: string[]
          technicalPreferences?: string[]
          constraints?: string[]
        }
        draftRun?: {
          idea?: {
            rawIdea?: string
            targetAudience?: string
          }
        }
        shieldMaxSeverity?: string
      }
    } catch {
      return {}
    }
  }

  private formatRole(role: string) {
    return role
      .split('_')
      .map((word) => word[0]?.toUpperCase() + word.slice(1))
      .join(' ')
  }
}
