import { Injectable } from '@nestjs/common'
import type {
  LlmProvider,
  LlmProviderRequest,
  LlmProviderResponse,
} from './llm.types.js'
import {
  createUsage,
  estimateMessageTokens,
  estimateTokens,
} from './llm.utils.js'

const mockJsonPrefix = 'MOCK_JSON:'

@Injectable()
export class MockLlmProvider implements LlmProvider {
  readonly providerId = 'mock' as const

  async completeJson(
    request: LlmProviderRequest,
  ): Promise<LlmProviderResponse> {
    const rawText = this.resolveMockJson(request)

    return {
      rawText,
      usage: createUsage(
        estimateMessageTokens(request.messages),
        estimateTokens(rawText),
      ),
      providerId: this.providerId,
      model: request.model,
    }
  }

  private resolveMockJson(request: LlmProviderRequest) {
    const explicitMock = [...request.messages]
      .reverse()
      .map((message) => message.content)
      .find((content) => content.includes(mockJsonPrefix))

    if (explicitMock) {
      return explicitMock.slice(
        explicitMock.indexOf(mockJsonPrefix) + mockJsonPrefix.length,
      )
    }

    if (request.taskName === 'triage/v1') {
      return JSON.stringify(this.createTriageResponse(request))
    }

    if (request.taskName.startsWith('agents/')) {
      return JSON.stringify(this.createAgentResponse(request))
    }

    if (request.taskName === 'moderator/v1') {
      return JSON.stringify(this.createModeratorResponse(request))
    }

    if (request.taskName === 'artifacts/executive_summary/v1') {
      return JSON.stringify(this.createExecutiveSummaryResponse(request))
    }

    if (request.taskName === 'artifacts/prd/v1') {
      return JSON.stringify(this.createPrdResponse(request))
    }

    if (request.taskName === 'artifacts/development_prompt/v1') {
      return JSON.stringify(this.createDevelopmentPromptResponse(request))
    }

    return JSON.stringify({
      summary: `Mock response for ${request.taskName}`,
    })
  }

  private createTriageResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const text = [
      payload.idea?.rawIdea,
      payload.idea?.targetAudience,
      ...(payload.idea?.strategicGoals ?? []),
      ...(payload.idea?.technicalPreferences ?? []),
      ...(payload.idea?.constraints ?? []),
    ]
      .join(' ')
      .toLowerCase()
    const securitySensitive =
      payload.shieldMaxSeverity === 'high' ||
      /security|appsec|auth|payment|fintech|compliance|privacy/.test(text)
    const mobileDomain = /mobile|ios|android|react native/.test(text)
    const complexity = /enterprise|multi-tenant|temporal|orchestrator|scale/.test(
      text,
    )
      ? 'high'
      : text.length > 600
        ? 'medium'
        : 'low'
    const recommendedAgents = [
      'product_manager',
      'critic',
      'moderator',
      ...(securitySensitive ? ['security_expert'] : []),
      ...(complexity === 'high' ? ['software_architect'] : []),
      ...(/market|competitor|pricing|gtm|go-to-market/.test(text)
        ? ['market_researcher']
        : []),
      ...(mobileDomain ? ['mobile_ux_expert'] : []),
    ].slice(0, 7)

    return {
      domain: mobileDomain ? 'mobile' : securitySensitive ? 'security' : 'software',
      subdomain: securitySensitive ? 'Security-sensitive software' : 'SaaS planning',
      complexity,
      marketConfidence: /new market|unknown|validate|competitor/.test(text)
        ? 'low'
        : 'medium',
      securitySensitivity: securitySensitive ? 'high' : 'medium',
      recommendedRunMode: recommendedAgents.length > 4 ? 'deep' : 'standard',
      recommendedAgents,
      estimatedDurationSeconds: recommendedAgents.length > 4 ? 150 : 60,
      estimatedMaxCostUsd: recommendedAgents.length > 4 ? 1.25 : 0.5,
      reasoningSummary:
        'Mock provider response generated through the prompt-driven LLM gateway.',
    }
  }

  private createAgentResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const idea = payload.draftRun?.idea?.rawIdea ?? 'the submitted idea'
    const targetAudience =
      payload.draftRun?.idea?.targetAudience ?? 'early adopters'
    const role = request.taskName.split('/')[1] ?? 'agent'

    return {
      summary: `${this.formatRole(role)} reviewed "${idea}" for ${targetAudience}.`,
      strengths: [
        'The workflow is structured and non-chat by design.',
        'Human review reduces the risk of expensive incorrect execution.',
      ],
      weaknesses: [
        'The current response is generated by the local mock provider.',
        'Real model quality still needs validation with provider adapters.',
      ],
      risks: [
        'Artifact quality can look convincing before assumptions are validated.',
      ],
      recommendations: [
        'Keep schema validation mandatory for every agent response.',
        'Track prompt version and model metadata for each output.',
      ],
      roleSpecificInsights: {
        role,
        providerMode: 'mock',
      },
    }
  }

  private createModeratorResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const draftRun = payload.draftRun ?? {}
    const approvedTriage = payload.approvedTriage ?? {}
    const agentOutputs = Array.isArray(payload.agentOutputs)
      ? payload.agentOutputs
      : []

    return {
      executivePositioning:
        'AI War Room turns raw product ideas into reviewed, build-ready artifacts through a structured council workflow.',
      targetUsers: [
        draftRun.idea?.targetAudience ?? 'Founders',
        'Technical product builders',
      ],
      coreProblem:
        'Builders need a repeatable path from rough idea to coherent PRD and implementation prompt.',
      proposedSolution:
        'Use Shield, approved triage, isolated specialists, and Moderator synthesis before generating final artifacts.',
      mvpScope: [
        'Idea submission',
        'Shield input scan',
        'Human Review Screen',
        'Prompt-driven isolated agent analysis',
        'Moderator synthesis',
        'Executive Summary, PRD, and Development Prompt',
      ],
      nonGoals: [
        'Custom user-defined agents',
        'Agent marketplace',
        'Open-ended multi-agent chat',
      ],
      keyDecisions: [
        `Use ${approvedTriage.recommendedRunMode ?? 'standard'} run mode for this draft.`,
        `Execute ${agentOutputs.length} non-moderator agents in isolation.`,
        'Keep Shield as a background security layer.',
      ],
      risks: agentOutputs
        .flatMap((agentOutput) => agentOutput.output?.risks ?? [])
        .slice(0, 10),
      openQuestions: [
        'Which artifact format should users export first?',
        'What quality signal proves that a generated development prompt is build-ready?',
      ],
      artifactGenerationBrief: {
        source: 'mock_prompt_driven_moderator',
        agentCount: agentOutputs.length,
        shieldStatus: draftRun.shieldScan?.status ?? 'clear',
      },
    }
  }

  private createExecutiveSummaryResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const draftRun = payload.draftRun ?? {}
    const moderatorSynthesis = payload.moderatorSynthesis ?? {}

    return {
      productIdea: draftRun.idea?.rawIdea ?? 'The submitted product idea',
      targetUsers: moderatorSynthesis.targetUsers ?? ['Founders'],
      coreValueProposition:
        moderatorSynthesis.proposedSolution ??
        'Generate validated product planning artifacts from a raw idea in minutes.',
      mainDifferentiator:
        'A structured non-chat pipeline with isolated agents and human approval.',
      mvpRecommendation:
        'Continue with the prompt-driven local flow and validate artifact usefulness.',
      topRisks: (moderatorSynthesis.risks ?? []).slice(0, 5),
      recommendation: 'go',
    }
  }

  private createPrdResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const moderatorSynthesis = payload.moderatorSynthesis ?? {}

    return {
      overview:
        moderatorSynthesis.proposedSolution ??
        'Create a structured planning workflow that turns ideas into artifacts.',
      goals: [
        'Create a repeatable idea-to-artifacts workflow.',
        'Keep execution structured and schema-validated.',
        'Protect the pipeline with Shield checks.',
      ],
      nonGoals: moderatorSynthesis.nonGoals ?? [],
      userPersonas: moderatorSynthesis.targetUsers ?? ['Founders'],
      userJourneys: [
        'User submits a raw idea and target audience.',
        'System scans input and triages the draft.',
        'User reviews metadata and selected agents.',
        'System executes prompt-driven agents and produces artifacts.',
      ],
      functionalRequirements: [
        'Submit idea draft.',
        'Display Shield findings with highlighted spans.',
        'Allow triage metadata edits.',
        'Allow selected agent edits.',
        'Generate Executive Summary, PRD, and Development Prompt.',
      ],
      nonFunctionalRequirements: [
        'Validate all generated objects with shared schemas.',
        'Record prompt version and model metadata for generated outputs.',
      ],
      mvpScope: moderatorSynthesis.mvpScope ?? ['Prompt-driven planning flow'],
      futureScope: [
        'Temporal orchestration',
        'Real provider adapters',
        'SSE artifact streaming',
      ],
      securityConsiderations: [
        'Treat user input as untrusted.',
        'Keep Shield findings separate from general product reasoning.',
      ],
      successMetrics: [
        'Draft run completion rate.',
        'Artifact copy/export rate.',
        'User approval rate after Human Review.',
      ],
      openQuestions: moderatorSynthesis.openQuestions ?? [],
    }
  }

  private createDevelopmentPromptResponse(request: LlmProviderRequest) {
    const payload = this.extractPayload(request)
    const completedPrd = payload.completedPrd ?? {}

    return {
      productSummary:
        completedPrd.overview ??
        'Build the approved AI War Room product described by the PRD.',
      technicalStack: ['Vite', 'React', 'TypeScript', 'NestJS', 'Fastify', 'Zod'],
      architectureOverview:
        'Use a monorepo with web, api, and shared schema packages. Route all model calls through the LLM gateway.',
      requiredModules: [
        'Idea submission UI',
        'Human Review Screen',
        'Runs API',
        'Prompt-driven agent pipeline',
        'Artifact viewer',
      ],
      dataModel: [
        'DraftRun',
        'AgentExecutionResult',
        'ModeratorSynthesis',
        'Artifact',
      ],
      apiRequirements: [
        'POST /api/runs/draft',
        'POST /api/runs/mock-pipeline',
        'GET /api/runs/capabilities',
      ],
      uiRequirements: [
        'Show agent step statuses.',
        'Render generated artifacts after execution.',
        'Keep Shield warnings compact and contextual.',
      ],
      securityConstraints: completedPrd.securityConsiderations ?? [
        'Treat user input as untrusted.',
      ],
      testingRequirements: [
        'Validate prompt-driven pipeline response schema.',
        'Test Shield detection and agent routing.',
        'Run build, lint, typecheck, and tests before committing.',
      ],
      implementationOrder: [
        ...(completedPrd.functionalRequirements ?? []).slice(0, 5),
        'Verify generated artifacts with schema tests and runtime checks.',
      ],
      outOfScope: completedPrd.nonGoals ?? [],
    }
  }

  private extractPayload(request: LlmProviderRequest) {
    const content = [...request.messages]
      .reverse()
      .map((message) => message.content)
      .find((message) => message.includes('INPUT_JSON:'))

    if (!content) {
      return {}
    }

    try {
      return JSON.parse(content.slice(content.indexOf('INPUT_JSON:') + 11)) as {
        idea?: {
          rawIdea?: string
          targetAudience?: string
          strategicGoals?: string[]
          technicalPreferences?: string[]
          constraints?: string[]
        }
        draftRun?: {
          idea?: {
            rawIdea?: string
            targetAudience?: string
          }
          shieldScan?: {
            status?: string
          }
        }
        shieldMaxSeverity?: string
        [key: string]: any
      }
    } catch {
      return {}
    }
  }

  private formatRole(role: string) {
    return role
      .split('_')
      .map((word) => word[0]?.toUpperCase() + word.slice(1))
      .join(' ')
  }
}
